
/* add test products */
INSERT INTO product (prod_name, category_id, prod_desc, prod_feature1, prod_feature2, prod_feature3, prod_feature4, prod_price, prod_in_stock, date_expires)
VALUES ("Moo Moo Vitta's Whole Milk",
5,
"It is basically from cow to table! Our milk has no artificial growth hormones. It is backed by our freshness guarantee to ensure it's ready for your cereal waiting at home.",
"Whole milk",
"Gluten free",
"1 gallon",
"Recycleable jug",
1.95,
1,
8
),
("Kraft Cheese Slices",
5,
"Only premium quality, real milk is used to prepare these delicious cheese slices. Enjoy the creamy melt of Kraft Singles on your next burger, sandwich, or grilled cheese.",
"Always made with milk",
"Pasteurized prepared cheese",
"12 oz (340g)",
"16 slices",
1.95,
1,
18
),
("On-the-go Yogurt",
5,
"This variety pack of Berry and Strawberry portable, low fat yogurt tubes is gluten free. A good source of vitamin D and calcium and is made with no high fructose corn syrup, and no colors or flavors from artificial sources.",
"No fructose corn syrup or artificial flavors",
"Contains dairy and eggs",
"Only 8g of sugar",
"32 tubes",
5.95,
1,
12
),
("Grade A Large Eggs",
5,
"Only premium quality, real milk is used to prepare these delicious cheese slices. Enjoy the creamy melt of Kraft Singles on your next burger, sandwich, or grilled cheese.",
"Large white eggs",
"12 eggs per carton",
"Always fresh as if it was farm to table!",
"Fragile",
0.95,
1,
12
),
("Half Vanilla / Half Chocolate Ice Cream",
4,
"Yummy, cold soft-serve ice-cream One half, vanilla. The other half, chocolate. Win-win!",
"Contains milk and soybean",
"Low fat",
"16 oz",
"Recycleable container",
1.95,
1,
8
),
("Combination Pizza",
4,
"Sausage & pizza topping with pepperoni seasoning. Sausage made with chicken and pork; Pizza topping with pepperoni seasoning made with pork, chicken, beef.",
"Original crispy crust",
"Stackable packaging to save freezer space",
"Perfect size for toaster oven",
"10.7 oz",
2.95,
1,
8
),
("Frozen Dinner Meal",
4,
"Roast beef patty topped with grilled onions and gravy with macaroni and cheese. No preservatives.",
"Highest quality ingredients",
"Contains milk, soy, anchovy & wheat",
"Microwaveable",
"9.5 oz",
3.95,
1,
8
),
("The Evil Dead",
8,
"The film focuses on five college students vacationing in an isolated cabin in a remote wooded area. After they find an audio tape that releases a legion of demons and spirits, members of the group suffer from demonic possession, leading to increasingly gory mayhem.",
"1981",
"American supernatural horror film starring Bruce Campbell, Ellen Sandweiss & Betsy Baker",
"American supernatural horror film written and directed by Sam Raimi",
"Produced by Sam Raimi & Bruce Campbell",
14.95,
1,
8
),
("Evil Dead II",
8,
"A parody sequel to the horror film The Evil Dead (1981). The film stars Bruce Campbell as Ash Williams.",
"1987",
"Written by Raimi and Scott Spiegel",
"American comedy horror film directed by Sam Raimi",
"Produced by Robert Tapert",
14.95,
1,
6
),
("Army of Darkness",
8,
"American dark fantasy comedy horror film starring Campbell and Embeth Davidtz, it is the third installment in the Evil Dead franchise, and continuing from Evil Dead II, and follows Ash Williams (Campbell) as he is trapped in the Middle Ages and battles the undead in his quest to return to the present.",
"1992",
"Starring Campbell and Embeth Davidtz, it is the third installment in the Evil Dead franchise, and continuing from Evil Dead II",
"Directed and co-written by Sam Raimi & co-written by Ivan Raimi. S",
"Co-produced by Robert Tapert and Bruce Campbell ",
14.95,
1,
16
),
("Pennywise: Straight Ahead",
10,
"Straight Ahead is the fifth studio album by the American punk rock band Pennywise. It was released on June 1, 1999 and features the radio hit single \"Alien\". The album was released by Epitaph Records, their long-time record label.",
"1999",
"Released by Epitaph Records",
"Includes hit track \"Alien\"",
"Punk rock, skate punk, melodic hardcore",
10.95,
1,
8
),
("Derek Will: Derek's PHP Anthem",
10,
"Listen to Derek give his insight on PHP through song. He sings about everything from getting lost in debugging to how tedious connecting files together can be.",
"2019",
"Self-Released",
"Includes hit track \"Fingers Crossed We Get This Project Done\"",
"Punk Rock, Gibberish, Frustratingly Stressed",
0.00,
1,
888
),
("Michael Jackson: Thriller",
10,
"\"Thriller\" is one of the definitive albums of the 1980s. The album won a record-breaking eight Grammy Awards in 1984, including Album of the Year. \"Thriller\" was recognized as the world's best-selling album on February 7, 1984, when it was inducted into the Guinness Book of World Records.",
"1982",
"Michael Jackson's sixth studio album",
"Includes hit track \"Thriller\"",
"Pop, Post-disco, Rock & Funk",
400.00,
1,
18
);

